name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-and-publish-code-coverage:
    name: Run tests and publish code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Tests and Generate Coverage Report
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}