name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  run-detekt:
    name: Run Detekt on the detekt rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Run Detekt on the detekt rules
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assemble detektMain
