name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  publish:
    name: Check that the publish plugin works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check that the publish plugin works
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal
  run-detekt:
    name: Run Detekt on the detekt rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Detekt on the detekt rules
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektMain
